const pgData = [
  {
    "id": 1,
    "name": "Sunrise PG Retreat",
    "image": "https://i.pinimg.com/1200x/da/2a/47/da2a47de9e45a211b525ec02c980ce8c.jpg",
    "city": "Kolkata",
    "location": "Salt Lake",
    "price": 5200,
    "bedrooms": "1",
    "amenities": ["Wi-Fi", "Power Backup", "Food"],
    "description": "Comfortable and peaceful accommodation in Salt Lake.",
    "propertyType": "PG",
    "status": "rent"
  },
  {
    "id": 2,
    "name": "Green Leaf PG",
    "image": "https://websiteupload.s3.ap-south-1.amazonaws.com/media/2024/07/6617bb86d89551.webp",
    "city": "Mumbai",
    "location": "Andheri",
    "price": 5900,
    "bedrooms": "2",
    "amenities": ["Wi-Fi", "Laundry", "Security"],
    "description": "Modern PG with green spaces in Andheri.",
    "propertyType": "PG",
    "status": "rent"
  },
  {
    "id": 3,
    "name": "Skyline Stay",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS1xDEPE0oqHSz-VG-osIYB4Z26_budc8Eb53uNUcbcIvh_GzAIDzl8o1-ItiTQR1W9y6Q&usqp=CAU",
    "city": "Delhi",
    "location": "Dwarka",
    "price": 5550,
    "bedrooms": "1",
    "amenities": ["Parking", "Wi-Fi", "Food"],
    "description": "Spacious PG close to metro, ideal for students.",
    "propertyType": "PG",
    "status": "rent"
  },
  {
    "id": 4,
    "name": "Urban Dream PG",
    "image": "https://img.staticmb.com/mbphoto/pg/grd2/cropped_images/2025/Jan/20/Photo_h400_w540/GR2-267087-2370725_400_540.jpeg",
    "city": "Chennai",
    "location": "T Nagar",
    "price": 5000,
    "bedrooms": "2",
    "amenities": ["Wi-Fi", "Food", "CCTV"],
    "description": "Affordable PG in T Nagar with excellent security.",
    "propertyType": "PG",
    "status": "rent"
  },
  {
    "id": 5,
    "name": "Lotus Nest PG",
    "image": "https://img.staticmb.com/mbphoto/pg/grd2/cropped_images/2024/Nov/13/Photo_h400_w540/GR2-471613-2308051_400_540.jpeg",
    "city": "Pune",
    "location": "Viman Nagar",
    "price": 6150,
    "bedrooms": "1",
    "amenities": ["Wi-Fi", "Laundry"],
    "description": "Serene surroundings at Lotus Nest.",
    "propertyType": "PG",
    "status": "rent"
  },
  {
    "id": 6,
    "name": "Palm Grove PG",
    "image": "https://rook.gumlet.io/uploads/center_caption_photo/photo/65143158be927a00017fe504/_MG_5595.jpg?compress=true&format=auto&quality=75&dpr=auto&h=auto&w=100%&ar=1.5",
    "city": "Hyderabad",
    "location": "Madhapur",
    "price": 5700,
    "bedrooms": "1",
    "amenities": ["Wi-Fi", "Meals", "Parking"],
    "description": "Comfortable rooms and wholesome meals.",
    "propertyType": "PG",
    "status": "rent"
  },
  {
    "id": 7,
    "name": "Vibrant Corner",
    "image": "https://rook.gumlet.io/uploads/center_caption_photo/photo/5dc5061f09ba996c9814db8c/4.jpg?compress=true&format=auto&quality=75&dpr=auto&h=auto&w=100%&ar=1.5",
    "city": "Bangalore",
    "location": "Indiranagar",
    "price": 6300,
    "bedrooms": "2",
    "amenities": ["Wi-Fi", "Security", "Power Backup"],
    "description": "Lively PG with all amenities around.",
    "propertyType": "PG",
    "status": "rent"
  },
  {
    "id": 8,
    "name": "Blue Bliss Stay",
    "image": "",
    "city": "Ahmedabad",
    "location": "Satellite",
    "price": 4800,
    "bedrooms": "1",
    "amenities": ["Wi-Fi", "Food"],
    "description": "Budget-friendly, peaceful surroundings in Satellite.",
    "propertyType": "PG",
    "status": "rent"
  },
  {
    "id": 9,
    "name": "The Haven PG",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_1cmXV0r9wKtGhFG1XF01jpVyFAKrPlrwNiMzypo6cEESpV9QWdOnYwmL8bw97O4wW0E&usqp=CAU",
    "city": "Kolkata",
    "location": "Rajarhat",
    "price": 5200,
    "bedrooms": "1",
    "amenities": ["Wi-Fi", "Laundry", "Food"],
    "description": "Warm, homely PG at Rajarhat area.",
    "propertyType": "PG",
    "status": "rent"
  },
  {
    "id": 10,
    "name": "Sunbeam Men's PG",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR_k2KDWdp_4Esw06hfQxRCEVc8dMJoxVpSjoKY-4xP4cDBHtWpzJ8_tHdJSQpmdJfAShE&usqp=CAU",
    "city": "Hyderabad",
    "location": "Gachibowli",
    "price": 6250,
    "bedrooms": "2",
    "amenities": ["Wi-Fi", "Power Backup"],
    "description": "Great for working professionals.",
    "propertyType": "PG",
    "status": "rent"
  },

]

export default pgData;